### ISSUE TITLE
Wind is showed in km/s even is changed to m/s

### ISSUE THREAD

**Issue by jukkaforss** [Gulivertx/cbatmo#10]
If I change unit from km/s to m/s, it changes km to ms, but numeric value is still km/s value.
Is this code bug, value not divided by 3.6?

**Comment by jukkaforss** [comment]
![cbatmo1](https://user-images.githubusercontent.com/47186678/75143741-85306280-56ed-11ea-96de-b29f1164c40d.jpg)
![cbatmo2](https://user-images.githubusercontent.com/47186678/75143745-86fa2600-56ed-11ea-9246-15be2d850117.jpg)
Images of values

**Comment by Gulivertx** [comment]
Hi same problem as https://github.com/Gulivertx/cbatmo/issues/9
I close this issue, please follow the issue 9 for the update.

**Comment by Gulivertx** [comment]
Fixed in the last commit :  https://github.com/Gulivertx/cbatmo/commit/890090b1064a4a87bf9bedf0dc63d54fae41f2bc
