### ISSUE TITLE
Is there a way I can translate it to English?

### ISSUE THREAD

**Issue by AndyMansson** [Gulivertx/cbatmo#14]
Hello Gulivertx, first I just wanted to say your project is the answer to my wishes.
Been looking for a way to display my Netatmo data in a nice way. And this is defiantly it.
Thank you.

I have had your previous version (2.0.0) for a while on my Mac, but will now go to Raspberry Pi and I saw that you have updated it. I would definitely like to use the nice new version.

As I read in your readme, you have plans to make it possible to have your application in English,
but it is not yet so. Is this something I could change myself? Or can I contribute somehow? (Not the best coder though...)

Thank you for a great application. And a great instruction for us new with Linux/Raspberry Pi.

**Comment by Gulivertx** [comment]
Hi, yep it is still in the pipeline to have En/Fr support. This is not a huge job, so I can do it in few days.

**Comment by AndyMansson** [comment]
Looking forward to that. Thank you. 🥇

**Comment by Gulivertx** [comment]
I re-open this issue and will close it when the job will be done.
