### ISSUE TITLE
How to edit .env

### ISSUE THREAD

**Issue by ocvelbye** [Gulivertx/cbatmo#23]
Hi and thank you for this software. 

I have a problem with the .env file. I can find the .env.dist file, but I cannot, or I dont understand how to copy it and editing it. Is there any chance someone can help? Im using a Mac with Mojave. 

Thanks

**Comment by Gulivertx** [comment]
hi, you just have to copy past the file **.env.dist** to .env and edit it.

**Comment by ocvelbye** [comment]
Thanks but where do I edit it? What kind of editor?


10. mai 2020 kl. 21:33 skrev Cedric Bapst <notifications@github.com>:

﻿

hi, you just have to copy past the file .env.dist to .env and edit it.
