### ISSUE TITLE
Integration Status-Symbol of Sensors

### ISSUE THREAD

**Issue by karba71** [Gulivertx/cbatmo#30]
Hello Cedric,

i have 1 wish for your next version.
Can you integrate this status-symbols of the sensors?
I can't see this symbols on my mobile, only on my PC.

<img width="210" alt="Netatmo Status" src="https://user-images.githubusercontent.com/56199098/83571866-e0fa5b00-a528-11ea-908a-31d9d4d01a0b.PNG">

in this way:
<img width="960" alt="cbatmo" src="https://user-images.githubusercontent.com/56199098/83571900-ed7eb380-a528-11ea-9927-ef65fef4632c.PNG">

**Comment by Gulivertx** [comment]
Yes I can, would be available for next release.

**Comment by Gulivertx** [comment]
Sorry but I did not have enough time these last days to release this with the version 2.3.2. I’m very busy for another huge project which must be done last month 😓

**Comment by karba71** [comment]
Hello Cedric,

no prob, i can wait.

I will test your new version 2.3.2 in this time

Karba

**Comment by Gulivertx** [comment]
ok I think I have something OK, not perfect but working
![](http://gulivert.ch/cbatmo_status_icons.png)

What do you think ?

**Comment by karba71** [comment]
Hello Cedric,

looks like perfect!


Karba

**Comment by Gulivertx** [comment]
Hi there, sorry for the long delay....
So I plane a new release for one of the next week which will integrate this.

**Comment by karba71** [comment]
**Hello**

I have testet this days on my 7"-LCD (before only at my pc).
I think the status-symbols should be colored (similar netatmo pc-app).
Actually it's very difficult to distinguish.

<img width="379" alt="Status-Symbole 20 11 20" src="https://user-images.githubusercontent.com/56199098/99818950-23533b00-2b4f-11eb-8611-765854b3e77c.PNG">


<img width="847" alt="status-symbole color" src="https://user-images.githubusercontent.com/56199098/99818884-0e76a780-2b4f-11eb-90ae-cae7134e1c8f.PNG">

Karba
