### ISSUE TITLE
changing data in the graph

### ISSUE THREAD

**Issue by karba71** [Gulivertx/cbatmo#31]
Hello Cedric,

I can changing the data in graph by klick on the data:
I can take data from the 2. indoor-module (temp, CO2, acoustic), the the outdoor-module (temp, humidity, pressure), the rain-sensor and the wind-sensor.

But, if i take any data from the main-module cbatmo breakes.

**Comment by Gulivertx** [comment]
I can reproduce this as well, will be fix with next release.

**Comment by karba71** [comment]
Contrary to mine first post:

I can tap on the pressure, **it comes from the main-module** and works fine.
But the others (temp, co2, humidity) didnt work.

Is the problem not by the sensor rather by the gui?

**Comment by Gulivertx** [comment]
it should work without any problem, did you use the branch deploy_script for your test ?
