### ISSUE TITLE
Tapping indoor temperature twice --> screen will only show background image

### ISSUE THREAD

**Issue by roineantti** [Gulivertx/cbatmo#38]
If you tap Indoor temperature twice, all meters will disappear and it shows only background image. This is tested with Raspberry Pi + Chromium and with Windows 10 + Edge Chromium. 
![issue-bg](https://user-images.githubusercontent.com/67387617/85613446-8b662980-b662-11ea-9b07-f9d2ecffb52f.png)

**Comment by Gulivertx** [comment]
it seems to be related to this issue which is fixed in the branch deploy_script (not yet available in master branch but for the next release) https://github.com/Gulivertx/cbatmo/issues/31
