### ISSUE TITLE
missing translation Humidity -> Luftfeuchtigkeit at graph

### ISSUE THREAD

**Issue by karba71** [Gulivertx/cbatmo#41]
**Hello Cedric,**

Thanks for V2.3.2!
We have some rain today and there is now shaking at my cbatmo!!!

I think there is a missing translation:
<img width="747" alt="Luftfeuchtigkeit" src="https://user-images.githubusercontent.com/56199098/86411203-9e10dc00-bcbc-11ea-84e3-6ff5b86f2395.PNG">

**Comment by Gulivertx** [comment]
Re-opened the scroll issue for the shaking problem : https://github.com/Gulivertx/cbatmo/issues/26

Hmm ha ok sounds like I forget to use the translator for the chart labels. Thanks for the report
