### ISSUE TITLE
V2.3.4; Station-Name overlays Time

### ISSUE THREAD

**Issue by karba71** [Gulivertx/cbatmo#45]
Hello Cedric,

Thanks for update to V2.3.4 with integrate of this status-symbols.

In this version the name of the station is very long and overlays the Time from the last data.
I think this was better in V2.3.3 (and i know my adress).

V2.3.3
![20200603_094222_resized](https://user-images.githubusercontent.com/56199098/99738436-c31ab580-2aca-11eb-8de3-42963e48043a.jpg)

V2.3.4
![Inked20201120_004354_resized (002)_LI](https://user-images.githubusercontent.com/56199098/99738450-cf067780-2aca-11eb-8d5c-f728733fde80.jpg)

Karba

**Comment by Gulivertx** [comment]
I did not change anything on this part in the last version. Station Uhlestrasse 34.... is your station name, you should rename your station in the Netatmo Application.
And what is coming inside the brackets is the main module name but it is not a choice from my side but a change that Netatmo did on their API, the station name now concatenate this value between bracket. Unfortunately this not something I have the hands on.
I could trim the name but this is not something I want to do myself. I dod not know why Netatmo change that!

**Comment by karba71** [comment]
Hello Cedric,

 

thanks.

 

I have check this.

 

V2.3.3 shows this long name too.

I think Netatmo have change here anything.

 

 

Karba

 

Von: Cedric Bapst <notifications@github.com> 
Gesendet: Freitag, 20. November 2020 08:57
An: Gulivertx/cbatmo <cbatmo@noreply.github.com>
Cc: Karba <KarstenBarth@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [Gulivertx/cbatmo] V2.3.4; Station-Name overlays Time (#45)

 

I did not change anything on this part in the last version. Station Uhlestrasse 34.... is your station name, you should rename your station in the Netatmo Application.
And what is coming inside the brackets is the main module name but it is not a choice from my side but a change that Netatmo did on their API, the station name now concatenate this value between bracket. Unfortunately this not something I have the hands on.
I could trim the name but this is not something I want to do myself. I dod not know why Netatmo change that!

**Comment by karba71** [comment]
Hello,

fixed, it was my mistake!

V2.3.3 its the same - i have change the name and then (the name is to long) we have this overlay.

Karba

**Comment by karba71** [comment]
fixed, it was my mistake!
