### ISSUE TITLE
status-symbols should be colored

### ISSUE THREAD

**Issue by karba71** [Gulivertx/cbatmo#46]
**Hello**

I think the status-symbols should be colored (similar netatmo pc-app).
Actually it's very difficult to distinguish.

Status-Symbole 20 11 20
<img width="379" alt="Status-Symbole 20 11 20" src="https://user-images.githubusercontent.com/56199098/101227283-93a5a480-3697-11eb-8be6-1183fb0d5251.PNG">

Karba

**Comment by Gulivertx** [comment]
Hi,
Sounds like good idea, where did you find the graphic resources?

**Comment by karba71** [comment]
Hello,

this pictures are from my netatmo pc-app.
![battery_low](https://user-images.githubusercontent.com/56199098/101241182-44da2800-36f4-11eb-9d3c-836a8bceb12c.png)
![battery_medium](https://user-images.githubusercontent.com/56199098/101241184-49064580-36f4-11eb-8265-40d23f170e91.png)
![battery_high](https://user-images.githubusercontent.com/56199098/101241186-502d5380-36f4-11eb-8e21-62b3e8622e58.png)
![module_int](https://user-images.githubusercontent.com/56199098/101241190-5d4a4280-36f4-11eb-9aac-ec7410424f3b.png)
![module_ext](https://user-images.githubusercontent.com/56199098/101241194-61766000-36f4-11eb-8b61-f3f1c90cdcc3.png)
![module_wind](https://user-images.githubusercontent.com/56199098/101241201-663b1400-36f4-11eb-8df2-1367c2de5803.png)
![module_rain](https://user-images.githubusercontent.com/56199098/101241204-6a673180-36f4-11eb-8e72-92af5ccbe9ab.png)
![signal_low](https://user-images.githubusercontent.com/56199098/101241209-7521c680-36f4-11eb-8c83-a33afd9c7a1a.png)
![signal_high](https://user-images.githubusercontent.com/56199098/101241212-79e67a80-36f4-11eb-9594-493b64c09ba5.png)
![signal_full](https://user-images.githubusercontent.com/56199098/101241220-7eab2e80-36f4-11eb-8a31-56f485262a34.png)
![wifi_full](https://user-images.githubusercontent.com/56199098/101241235-89fe5a00-36f4-11eb-9cdb-80bd9263be99.png)

You mean this symbols?
Some symbols are missing, i will look for this.

**Comment by karba71** [comment]
![signal_medium](https://user-images.githubusercontent.com/56199098/101243134-73f59700-36fe-11eb-803b-16279cc01384.png)

**Comment by karba71** [comment]
![signal_verylow](https://user-images.githubusercontent.com/56199098/101280223-3fe6a880-37c8-11eb-8bd3-5dff100b6869.png)

**Comment by karba71** [comment]
![battery_full](https://user-images.githubusercontent.com/56199098/101280461-78d34d00-37c9-11eb-8a45-57fae0325cf3.png)

**Comment by karba71** [comment]
![battery_unknown](https://user-images.githubusercontent.com/56199098/101283828-44698c00-37dd-11eb-9a6f-fdef3bfaf5d3.png)

![signal_unknown](https://user-images.githubusercontent.com/56199098/101283833-4b909a00-37dd-11eb-9f4f-4cdbd8a3f8d1.png)

**Comment by karba71** [comment]
![wifi_high](https://user-images.githubusercontent.com/56199098/101996391-41393900-3cd2-11eb-8b70-fbae65cde020.png)
![wifi_medium](https://user-images.githubusercontent.com/56199098/101996393-41d1cf80-3cd2-11eb-91a7-411fc78eb2dd.png)
![wifi_low](https://user-images.githubusercontent.com/56199098/101996394-41d1cf80-3cd2-11eb-8560-43fab6411805.png)
![battery_verylow](https://user-images.githubusercontent.com/56199098/101996395-41d1cf80-3cd2-11eb-9117-0d353c0d47b4.png)

**Comment by karba71** [comment]
Hello,

I think this are all symbols.

Karba

**Comment by Gulivertx** [comment]
hmm, I think I cannot use this graphic resources, as they are propriety of Netatmo. I will look after the official developer documents if there is some information about. Anyway, thanks for the image.
