### ISSUE TITLE
Manual build fails wrong yarn version

### ISSUE THREAD

**Issue by exoticatom** [Gulivertx/cbatmo#52]
Hi, can you pls help.
I did manual build on my PC and transferred ZIP to raspi.
When I execute "yarn install --production" it fails:
![image](https://user-images.githubusercontent.com/26557176/103042155-f7294080-4578-11eb-974a-32456b722910.png)

any idea what could it be ?

thanks

**Comment by exoticatom** [comment]
Maybe this could help ?
![image](https://user-images.githubusercontent.com/26557176/103042523-3310d580-457a-11eb-89c9-bddc61abe9e7.png)

**Comment by exoticatom** [comment]
oh... lesson learned 
`sudo aptget -install yarn `

doesn't installs the correct version..

use: [Link to installation instructions](https://classic.yarnpkg.com/en/docs/install/#debian-stable)

Maybe update documentation? Yarn doesnt come preinstalled on raspi.

**Comment by Gulivertx** [comment]
Correct and you already had this problem in the past : https://github.com/Gulivertx/cbatmo/issues/29 ;)

**Comment by exoticatom** [comment]
oops , I clicked closed :-) Not sure if it should be like that.

yes, and I completely forgot about it. I had to rebuild the new version. Strange that I am the only one always having this issue with a strange yarn version.

**Comment by Gulivertx** [comment]
information about yarn added in README
