### ISSUE TITLE
difference betweeen Netatmo and cbatmo at WiFi-Status

### ISSUE THREAD

**Issue by karba71** [Gulivertx/cbatmo#55]
Hello,

cbatmo; V2.3.4

There is a difference betweeen Netatmo and cbatmo at WiFi-Status from my main-station (Wohnzimmer).
I think I have a good WiFi-Signal and the WiFi-Status is Full.
But cbatmo shows a lower signal.

<img width="439" alt="WiFi Wohnzimmer" src="https://user-images.githubusercontent.com/56199098/103316755-c7bb7d80-4a29-11eb-90fd-0ccf451260c4.PNG">

<img width="191" alt="WiFi-Status" src="https://user-images.githubusercontent.com/56199098/103316760-cc803180-4a29-11eb-95a2-4daedf176476.PNG">

Karba

**Comment by Gulivertx** [comment]
Hi, thanks to your report.
Hmm interesting, I actually used this information : https://dev.netatmo.com/apidocumentation/weather
Look at section Specifications.
Then in my code I used the given values : https://github.com/Gulivertx/cbatmo/blob/master/src/models/NetatmoNAMain.ts#L101-L114

**Comment by Gulivertx** [comment]
Should now be fixed with version 2.3.6
