### ISSUE TITLE
No Data Under Chambre of Mathias 

### ISSUE THREAD

**Issue by coldstream** [Gulivertx/cbatmo#8]
![2D1779E6-8192-40ED-90E1-5463A3AE3BE2](https://user-images.githubusercontent.com/704062/71764529-3a377180-2f2c-11ea-90b9-012dfce71418.jpeg)
Hi!
First! I appreciate the work you put into this!  I had quite a bit of fun figuring out how to get this on my Raspberry Pi (I bought the LCD screen after I saw this).  

For the issue, I'm out of ideas on why I don't see any weather data populating in the "Chambre of Mathias(sp?)" area.  It is blank here on my setup.  All the other fields are working great.  I am guessing this data is supposed to be populated by Darksky?  

If you need further info, please let me know!

Todd Osborne

**Comment by Gulivertx** [comment]
Hi, the missing data is an indoor additional Netatmo module. 
If you not have any additional indoor module this is normal to have this blank area. 
What I could do easily it’s to extend the rain module graph to use the whole available area if there is not any additional indoor module detected. 
Or if you want to propose a code correction to handle this it will also be great :)

**Comment by coldstream** [comment]
Hi!
I think if an additional module is missing, perhaps move the WIND up to RAIN GAUGE.  Then stretch the GRAPH section to accommodate the empty space left.  (see my image I uploaded for reference)

I think this is the best approach because the GRAPH can be changed depending on what module you tap on (RAIN, WIND, TEMP, etc.).  Keeping it somewhat separate might be more intuitive for pp. to change the graph.  My 2 cents!

Todd

**Comment by Gulivertx** [comment]
I close this issue as it related to https://github.com/Gulivertx/cbatmo/issues/13 which will also fix this.
