### ISSUE TITLE
Inconsistencies in Unit Type -> No values conversion according to user unit settings

### ISSUE THREAD

**Issue by coldstream** [Gulivertx/cbatmo#9]
![2D77552C-E5BD-438E-82A4-FFECA0D05F11](https://user-images.githubusercontent.com/704062/71764537-4fac9b80-2f2c-11ea-9928-e57d95366a7d.jpeg)
Opening a separate issue.  Some of my data is in Celsius while my forecast units are in Fahrenheit. Also, my Wind is in Imperial units (which is what I want). The current Indoor/Outdoor temperature readings are in Celsius.  I prefer to have them in Fahrenheit.  Please advise if I need to do something on my end to make them all in Fahrenheit.

DarkSky API call:
https://api.darksky.net/forecast/c0a15596c39f4fdac79a199538965bb7/35.65750591570345,139.72955911072637

**Comment by Gulivertx** [comment]
I need to investigate this, it seems that I forget to handle temperature unit... I will check this the next week

**Comment by Gulivertx** [comment]
Currently looking for this issue and it seems that Netatmo API do not return the values according to the user units settings.
I asked on the Netatmo forum, will see if I get an answer, but I feel like I will have to convert values myself.... Let's see.
https://forum.netatmo.com/viewtopic.php?f=5&t=17892

**Comment by Gulivertx** [comment]
From Netatmo response I have to concert myself all the values according to the user unit settings.

Will be available in the next app release.

**Comment by Gulivertx** [comment]
Fixed with the last commit : https://github.com/Gulivertx/cbatmo/commit/890090b1064a4a87bf9bedf0dc63d54fae41f2bc
